server:
  port: 8085

spring:
  data:
    mongodb:
      host: localhost
      username: banula_local
      password: minikube
      database: banula_local
      port: 27017
      authentication-database: admin

platform:
  url: http://localhost:9085/platform-platformoli
  party-id: DE
  country-code: OLI

party:
  url: http://localhost:8085