apiVersion: v2
name: banula-nsp
description: Banula Navigation Service (NSP)
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: oli-app
    version: "1.4.x"
    repository: "oci://ghcr.io/olisystems/charts"
