oli-app:
  fullnameOverride: "banula-navigation-service-dev"
  image:
    tag: "develop-56c9b80"
  ingress:
    hosts:
      - host: banula-dev.oli-system.com
    tls:
      - secretName: banula-dev-tls
        hosts:
          - banula-dev.oli-system.com
    features:
      router:
        routes:
          exposeAll: true
